alexflint/go-arg

usage.go, usage_test.go
This pr adds unittests for the printing of usage and help information. It also fixes a bug in which some usage information was not printed to the buffer.
=> add tests for usage info

usage.go, usage_test.go
When looking at `usage_test.go` I noticed that the tests started to fail because my editor removed the trailing whitespace from the usage line in `expectedHelp`.
This PR is to remove that excess whitespace from the usage line by prefixing each argument with a space rather than postfixing it.
We were able to do this easily since the `"usage: %s "` format had a trailing whitespace as well.
=> Remove excess trailing whitespace from Usage generation

usage.go
Hi! I really like your library, great work!
I saw that the fail message when something goes wrong with parsing is printed to stdout, I don't know if this is just preference, but I prefer to output that on stderr. I've got some backing here http://courses.cms.caltech.edu/cs11/material/general/usage.html but it's up to you to decide.
As I see it it's an error, even if it contains usage information also.
This patch does:
When the parsing of parameters/flags fails eg. when a required flag is
missing, print the usage statement and error to stderr instead of
stdout.
Tests are passing.
=> Write usage message to stderr on error

usage.go
I ran gometalinter on the project, and some warnings came up. This pull request fixes one of the (the easiest).
Output was
```
$ gometalinter .
usage.go:106:9:warning: if block ends with a return statement, so drop this else and outdent its block (golint)
parse.go:197::warning: cyclomatic complexity 30 of function process() is high (> 10) (gocyclo)
parse.go:94::warning: cyclomatic complexity 19 of function NewParser() is high (> 10) (gocyclo)
parse.go:345::warning: cyclomatic complexity 12 of function setScalar() is high (> 10) (gocyclo)
```
After patch
```
$ gometalinter .
parse.go:197::warning: cyclomatic complexity 30 of function process() is high (> 10) (gocyclo)
parse.go:94::warning: cyclomatic complexity 19 of function NewParser() is high (> 10) (gocyclo)
parse.go:345::warning: …
```
=> Fix lint warning

usage.go
Only the usage message was written to stderr, the error was written with
the standard fmt.Println.
I noticed this bug with my first pull request.
=> Fix bug with error not being written to stderr

doc.go, parse.go
A common way to structure package documentation when it's split over multiple files is to use a `doc.go` file. This pull request moves the documentation from `parse.go` to `doc.go`
Reference: http://blog.golang.org/godoc-documenting-go-code
=> Move package documentation to doc.go

parse.go, usage.go, usage_test.go
Adds help to the options in help output with an easy way to add more
built ins.
Help and version flags is usually shown in the help output. E.g. ls output
```
--help     display this help and exit
--version  output version information and exit
```
=> Add built ins to options in help output

usage.go, usage_test.go
We try to compare []strings, which are uncomparable types:
`panic: runtime error: comparing uncomparable type []string`
=> Fix error when printing usage for multi-value arguments

README.md, parse.go, parse_test.go
This pr changes MustParse to return the *Parser used to parse the command line options.
This makes it possible to do further validation of the arguments, and then use `parser.Fail` to print usage information together with a failure message:
```go
Foo string
Bar string
}
p := arg.MustParse(&args)
if args.Foo == "" && args.Bar == "" {
p.Fail("you must provide one of --foo and --bar)
}
```
=> MustParse returns *Parser

usage.go, usage_test.go
This pull request is dependent on #7, so please only review the HEAD commit https://github.com/alexflint/go-arg/commit/086eff38e4a73d3b1a7eff25cfb7d8be3b0d646f
This PR is to add support for the `help:` tag on positional arguments. It uses the same column width that is being used for options.
Here is the example generated from `usage_test.go`
```go
Input    string   `arg:"positional"`
Output   []string `arg:"positional,help:positional output"`
Verbose  bool     `arg:"-v,help:verbosity level"`
Dataset  string   `arg:"help:dataset to use"`
Optimize int      `arg:"-O,help:optimization level"`
}
```
```
usage: example [--verbose] [--dataset DATASET] [--optimize OPTIMIZE] INPUT [OUTPUT [OUTPUT ...]]
positional arguments:
input
output                 positional output
options: …
```
=> Display help text for positional arguments

README.md, parse.go, parse_test.go, usage_test.go
I decided to take a stab at #2 and this is what I came up with.
Adding in a new tag `env`, if provided, `go-arg` will look for an environment variable to preload the argument from. Using the tag on it's own `arg:"env"` by default it will use `strings.ToUpper(field.Name)` of the argument, or else you can override the name of the environment variable via `arg:"env:ENV_VAR"`.
=> Add support for environment variables

parse.go, parse_test.go, scalar.go
This pr adds support for `time.Duration` fields, using `time.ParseDuration` for string conversion:
```go
Timeout time.Duration
}
```
```
$ ./prog --timeout 13ms
```
It also moves `setScalar` to its own file, `scalar.go`, since it was getting quite long.
=> Add support for time.Duration fields

README.md, parse.go, parse_test.go, scalar.go
This pr makes it possible to use the `encoding.TextUnmarshaler` interface to implement custom argument parsers.
=> add support for pointers and TextUnmarshaler

parse.go, parse_test.go, scalar.go, usage.go
This pr adds support for `net.IP`, `net.HardwareAddr`, and `mail.Message`. Parsing is performed using the relevant standard library functions.
=> Parse IP addresses, MAC addresses, and email addresses

parse.go, parse_test.go
This is a failing test case, not to be merged.
I would like to hear from you what the intended behaviour is in this case.
Right now, when you set default values for a arg with multiple, the default values is not overridden, but the provided values are appended to the default values. But for non multiple the default value is overridden.
Is this intended behaviour? If that is the case, should we add some documentation about this in the README?
This caused me some head scratching before I figured out the cause, as I assumed the default values would be overridden. My workaround for this is at https://github.com/walle/lll/blob/971fc17f2a8231d15830f08835476e3170be495f/cmd/lll/main.go#L27-L50
If this is not the intended behaviour I could take a stab at fixing it in this pull request.
=> Defaults for multiples, intended behaviour

usage.go, usage_test.go
Default values for multiple-arguments is not printed in usage.
I have a workaround here https://github.com/walle/lll/blob/971fc17f2a8231d15830f08835476e3170be495f/cmd/lll/main.go#L18
This commit fixes the issue.
Please let me know if you have any comments on it.
Check if the default value supplied is a slice and not nil, if so
print the list of values supplied.
Test case for slice argument with and without default values.
Default values for slices was not printed because slice is not
comparable, but the zero value for slices is nil.
=> Print defaults for multiples

README.md, parse.go, usage.go, usage_test.go
This makes it possible to specify version strings as suggested by @brentp in #37 :
```go
type args struct {
...
}
func (args) Version() string {
return "someprogram 4.3.0"
}
func main() {
var args args
arg.MustParse(&args)
}
```
```shell
$ ./example --version
someprogram 4.3.0
```
```shell
$ ./example --help
someprogram 4.3.0
usage: version
options:
--help, -h             display this help and exit
--version              display version and exit
```
=> Add support for version strings

README.md, parse.go, parse_test.go
This pr adds support for embedded structs. Embedded struct fields are treated the same as first-order fields, unless the embedding field is amarked with `arg:"-"`, in which case that embedded struct is ignored.
=> add support for embedded structs

README.md, parse.go, usage.go, usage_test.go
We often need a more detailed description than the usage string.
=> add support for description string

parse.go, parse_test.go
Fixes a panic caused by `os.Args` being empty. This is not a situation I expect to come up often, but still we should not panic in this case.
=> Do not crash when os.Args is empty

parse.go, parse_test.go
This pr makes it possible to pass "-" as the value for an option or positional argument, as suggested by @mnsmar in #47. This fixes cases such as:
```
./myprog --version -
./myprog --users foo bar - baz
./myprog a - b
```
=> deal with "-" as option value

parse.go, parse_test.go, usage.go, usage_test.go
If []string "multiple" positional type is marked as required, it should expect at least one item in the array. The following pull request adds checks for that.
That also changes Usage string for "multiple" type depending on whether it is required:
- POSITIONAL [POSITIONAL ...]     (when required)
- [POSITIONAL [POSITIONAL ...]]    (when optional)
I also added couple of new tests for this functionality.
=> Required multiple positionals

parse.go, parse_test.go
as per issue #56 (https://github.com/alexflint/go-arg/issues/56)
=> Allow spaces after each comma in tags

README.md, doc.go, parse.go, parse_test.go, usage_test.go
Altered help tag parsing to reduce the constraints on help text content. In particular, comma or colon might be detected by the arg parser and might cause unexpected results.
So a new `help` tag is now supported and this is expected to be used alongside / instead of the `arg` tag.
The old behaviour is retained for backward compatibility
=> Altered help tag parsing to allow comma and colon

Godeps/Godeps.json, README.md, parse_test.go, vendor/github.com/alexflint/go-scalar/scalar.go
This PR updates go-scalar to the latest version bringing support for custom parsing for values in arguments structs and not only pointers.
=> Update go scalar to the latest version

.travis.yml, test/README.md, test/compile_with_go110.sh, test/compile_with_go111.sh, test/compile_with_go111_inside_gopath.sh, test/some-program/go.mod, test/some-program/go.sum, test/some-program/main.go
This PR adds tests that check that go-arg can be installed and compile under go 1.10 and go 1.11, both with and without the new Go module system active.
=> Tests for installation under go 1.10 and go 1.11

.travis.yml, README.md, example_test.go, go.mod, parse.go, parse_test.go, usage.go, usage_test.go
This pr introduces support for default values specified as struct tags:
```go
Foo int `default:"123"`
}
arg.MustParse(&args)
```
This means there are now two ways to provide default values. The old way still works as expected:
```go
Foo int
}
args.Foo = 123
arg.MustParse(&args)
```
The reason I'm introducing this feature is that it has now been requested many times, and the old approach does not work with subcommands (introduced in #82; see discussion in #86).
Fixes #40 #68 #86 #92
=> Allow default values in struct tags

README.md
Fixes #103
I started by adding to example_test.go, but it didn't work because Go "testable examples" expect the program to output to stdout, while in this case we are using stderr.
=> README: how to terminate a program when no subcommands are specified

example_test.go, usage.go, usage_test.go
Fixes #101 
Includes a change to the semantics of `WriteUsage` and `WriteHelp`. In particular, you can now call `p.Parse(args)` in a manner which includes a subcommand, and then the writers will pick up on that and print the help for the subcommand text instead.
This was needed to write a sane unit test for the usage fix, but it also seemed like a reasonable piece of functionality to add.
I don't think this should break userland, since relying on `p.Parse([]string{"subcommand"})` to _not_ update the WriteHelp/WriteUsage text would be batty. Still, if you have any concerns there, cecb4be is self-contained and can be taken alone.
=> Subcommand usage options

parse.go, parse_test.go, usage_test.go
This pr adds a boolean flag `IgnoreEnv` to the `Config` struct, which can be used to turn off all environment variable processing, as this test demonstrates:
```go
func TestEnvironmentVariableIgnored(t *testing.T) {
Foo string `arg:"env"`
}
setenv(t, "FOO", "abc")
p, err := NewParser(Config{IgnoreEnv: true}, &args)
require.NoError(t, err)
err = p.Parse(nil)
assert.NoError(t, err)
assert.Equal(t, "", args.Foo)
}
```
Closes #95
=> Option to ignore environment variables

usage.go, usage_test.go
The test case should be self-explanatory: this PR adds displaying of ENV variables in the usage output, so that one doesn't have to look at the code (which may not be provided) to understand which environment variables are accepted.
=> feat(usage): Include env variable in usage

README.md, example_test.go
This pr adds documentation and examples showing that it is possible to override either the short option name (-s), the long option name (--long), or both ("-s,--long"). 
Closes #121
=> Add examples showing how to override the short and long versions of option

parse.go, parse_test.go, reflect.go, reflect_test.go
Fixes #132 
Do not process unexported struct fields.
=> Skip unexported fields

.github/workflows/go.yml
This PR adds go1.15 to continuous integration, and drop go1.11
=> Add go1.15 to CI

README.md, parse.go, parse_test.go, usage.go, usage_test.go
(Pulling code written by @Andrew-Morozko over to a new branch in order to address comments.)
This PR makes it possible to have options that have short names but no long name, like this:
```go
ShortOnly string `arg:"-s,--"`
}
```
This field will respond to "-s" on the command line but not to any double-dash long name.
=> Optional long names

README.md, example_test.go, parse.go, parse_test.go, reflect.go, reflect_test.go, sequence.go, sequence_test.go, usage.go
Closes #148 
This pr makes it possible to parse into a map with code like this:
```go
M map[string]int
}
```
```bash
./myprogram --m foo=1 bar=2
```
I chose to have the values separated by space rather than commas because support for commas can be implemented using a custom TextUnmarshaler
=> Add support for parsing into a map

example_test.go, parse.go, parse_test.go, reflect.go, reflect_test.go, subcommand_test.go, usage.go, usage_test.go
This PR pushes up test coverage to 100% by:
- adding several extra tests
- refactoring the monkey-patching of os.Exit, os.Stdout, os.Stdin
- cleaning up the tests that inject environment variables
=> Push test coverage up to 100%

example_test.go
This pr adds a runnable example of parsing values into a map when the key=value entries are separated by commas, as in:
```shell
./example --mymapping a=b,c=d,e=f
```
=> Add an example of mappings with commas

parse.go, parse_test.go
This pr fixes the case where an empty environment variable is parsed in a slice or map.
See #148
=> Fix case where an empty environment variable is parsed in a slice or map

parse.go, parse_test.go
Fixes #157 
This PR makes it so that exported fields on unexported embedded structs still show up as flags. This was a regression in v1.4.0.
=> Recurse into unexported embedded structs

README.md, example_test.go, go.mod, go.sum, parse_test.go
This pull request adds support parsing URLs:
```go
URL url.URL
}
arg.MustParse(&args)
```
It also adds documentation about the full range of types supported by go-arg.
Closes #161
=> Add support for URLs

parse.go, parse_test.go
Fixes #165 
This pull request adds the name of the relevant environment variable to error messages
```
NEW:
error: --foo is required (or environment variable FOO)
OLD:
error: --foo is required
```
If no environment variable is associated with an argument then nothing is changed in the error message.
=> Put name of environment variable in error message

README.md, parse.go, parse_test.go
The ability to ignore default values can be used to override values in a struct already populated by a configuration file.
=> Add 'IgnoreDefault' option

README.md, parse.go, usage.go, usage_test.go
Similar to the `Description` at the top of the help text an `Epilogue` can be added at the bottom.
Resolves #189
=> Feat: Add epilogue after help text

go.mod, go.sum, parse_test.go
Latest go-scalar has support for hex, oct, and binary integer literals
=> Update to latest go-scalar

parse.go, parse_test.go
This moves most of the body of the MustParse function into a MustParse method on a Parser. The MustParse function is now implemented by calling the MustParse method on the Parser it implicitly creates.
Closes: #194
=> Implement MustParse on Parser

go.mod, parse.go, parse_test.go, reflect.go, usage.go, usage_test.go
=> Do not turn values intro strings and then back into values when processing default values

go.sum, parse.go, parse_test.go
Add option to parser to disallow global flags after subcommand name
Sometimes it's helpful to have a more strict command ordering
Tests added
=> add strict subcommand parsing

parse.go, usage.go
go-arg is a great job for terminal use. And I need to support parameter parsing in web scenarios, so I extended some of the code. Terminal is supported by default. When need to support other scenarios, users can customize standard input and output.
=> feat: support more env than terminal

example_test.go, parse.go, parse_test.go, usage.go, usage_test.go
Following very helpful pull request #210, here I clean up a few different ways that it was previously possible to customize the exit function and output writer used by MustParse and friends.
Note @cabuda this changes the interface in your pr a bit. Now the config struct just contains fields "Out" and "Exit".
=> clean up customizable stdout, stderr, and exit in parser config

example_test.go, parse.go, parse_test.go, usage.go, usage_test.go
Args from CLI can be disabled by "nulling" them using dashes without a value. 
- Closes #179 
- Continuation of #182 (@padilo) 
```golang
ApiKey   string     `arg:"required,-,--,env:API_KEY" help:"Only via env-var for security reasons"`
Trace      bool     `arg:"--,env" help:"Record low-level trace"`
}
```
```bash
Usage: example [--arg ARG]
Options:
--arg ARG, -a ARG [env: MY_ARG]
--help, -h             display this help and exit
Environment variables:
API_KEY                 Required. Only via env-var for security reasons
TRACE                   Optional. Record low-level trace
```
=> Support for parameters which can only be passed via env

parse.go, parse_test.go, usage.go
I noticed that when the destination struct is not versioned, the parser still accepts a `--version` flag but prints nothing.
This PR fixes the issue by implementing the following improvements to the version flag handling:
* Only use/show builtin `--version` flag if args are versioned with a non-empty `Version()`
* If args define a `--version` flag, honor it and disable/hide the builtin version flag
* Only return `ErrVersion` when using the builtin version flag
This allows developers to freely define and use their own `--version` flag if they need in the destination struct.
Note that if args defines a `--version` flag, it always overrides the builtin version flag, even if args has `Version()`.
I also split the `TestVersion` test into separate test for each versioning case.
Thanks for this …
=> Improve handling of version flag

parse.go, parse_test.go, subcommand.go, subcommand_test.go, usage.go, usage_test.go
With this PR it is possible to define aliases for subcommands like this:
```go
Remove *struct{} `arg:"subcommand:remove|rm|r" help:"remove something from somewhere"`
}
```
You can then write `./myprogram remove` or `./myprogram rm` or `./myprogram r`
They show up in the help output like this:
```
Usage: example <command> [<args>]
Options:
--help, -h             display this help and exit
Commands:
remove, rm, r          remove something from somewhere
```
Originall I wanted to use tag syntax `subcommand:remove,rm,r` but I couldn't because the commas are already defined to be a separator at a higher level so it would create trouble to write something like `subcommand:blah,help:something`. I decided to go with pipes instead.
Closes #230
=> add subcommand aliases

parse.go, usage.go, usage_test.go
When the user explicitly sets the placeholder to empty, we change the usage text so that there aren't extraneous spaces:
```
Something `arg:"-s" placeholder:"" help:"some help for something"`
}
```
```
...
Options:
-s, --something    some help for something
...
```
Previous this would have printed usage text with some extraneous spaces: `-s , --something`
Closes #241
=> Handle explicit empty placeholders

example_test.go, parse.go, parse_test.go
This simple PR adds a test case for the package-level `MustParse` for invalid structs and fixes a crash that occurs in this case.
Fixes #254
=> Fix crash on errors in package-level `MustParse`

parse.go, parse_test.go, usage.go, usage_test.go
The stdlib `flag` package (specifically [`ExitOnError`](https://pkg.go.dev/flag#ErrorHandling)) and most command line utilities use status code `2`.
I tried to find proper sources for common exit status codes, however these are the best I could find:
From: <https://stackoverflow.com/a/40484670>
> Exit status 0: success
> Exit status 1: "failure", as defined by the program
> Exit status 2: command line usage error
From: <https://tldp.org/LDP/abs/html/exitcodes.html>:
> 2 | Misuse of shell builtins (according to Bash documentation)
More importantly, currently using `-1` (which translates to 255) is actually documented as a bad choice in [`os.Exit`](https://pkg.go.dev/os#Exit):
> For portability, the status code should be in the range [0, 125].
Fixes #246
=> Use standard exit status code for usage errors

README.md
If you want to specify both of these, and if they should have different
names, then this shows you how it can be done.
=> add an example for environment vars with arg names

README.md, usage.go, usage_test.go
Hi @alexflint , this is a small follow-up to PR #223 :)
I realized that I forgot to update the write usage function, and it was still printing the output of `Version()` even if a custom `--version` flag spec is present in the arguments. This is now also fixed and I added more unit tests for help/usage writing.
I also took the opportunity to improve a bit the way version flag specs are scanned for both usage and help writing.
I belive that this PR now fully addresses issue #171 because, when using a custom `--version` flag, the builtin version string (if any) is not printed anymore in usage and errors.
Fixes #171
=> Fix usage writing when using custom version flag

example_test.go
The output of the testable example `Example_helpPlaceholder` is not working correctly due to wrong formatting.
Observe the example in [pkg.go.dev](https://pkg.go.dev/github.com/alexflint/go-arg#example-package-HelpPlaceholder) and note how the Output section is empty.
This simple PR fixes the formatting so the Output section works correctly.
I discovered this issue while running `golangci-lint` over the repository :)
=> Fix testable example output comment formatting

README.md, parse.go
Add some notes about the way that Parse() returns ErrHelp and ErrVersion when --help and --version are written on the command line.
=> Update API docs for Parser.Parse

usage.go, usage_test.go
This simple PR fixes the linked issue below.
Writing the version on usage text is unexpected and confusing.
Resolves #193
=> Move writing program version from usage to help writer

usage.go, usage_test.go
This simple PR fixes the help text for positional arguments with default values and environment variables.
Fixes #261
=> Fix help text for positional args with default and env var

parse.go, parse_test.go
Passing the no-more-options string "--" twice or more should pass the second and subsequent ones through as positionals. This makes it possible to pass the string "--" as a positional:
```go
X []string `arg:"positional"
}
arg.MustParse(&args)
```
```shell
./example -- test test2 -- test3  // args.X is [test, test2, --, test3]
```
=> Passing the no-more-options string "--" twice or more

README.md, parse.go, parse_test.go
This PR implements support for setting a global env var prefix (see linked issue).
While writing common reusable args structs for our Go programs today, I realized on the value and usefulness of this feature in real-world applications and decided to implement it for `go-arg`.
The implementation adds a new `EnvPrefix` field in `Config` and therefore is only accessible when using `NewParser()`.
Because the implementation adds the prefix to `spec.env`, the prefix is reflected everywhere, including usage help text.
To write the unit test, I had to extend `parseWithEnv` so a `Config` can be passed instead of hard-coding `Config{}`.
And last but not least, an example in the README was using `os.Args` instead of `os.Args[1:]` in `p.Parse()`. This probably came from a very outdated version, but I …
=> Add support for setting a global env var prefix

parse.go
Solves https://github.com/alexflint/go-arg/issues/275
Used the common `spec.placeholder` property for usage and errors. This property is set in [`cmdFromStruct`](https://github.com/alexflint/go-arg/blob/master/parse.go#L413-L421) and has sensible fallback, so it made sense to use it as the main output representation.
Didn't write any additional tests, due to current ones not testing the actual output strings and wanted to keep it that way.
=> Make field name output consistent when using placeholders

parse.go
```go
package main
import "github.com/alexflint/go-arg"
type Subcmd1 struct{}
type Arg1 struct {
Option1 string   `arg:"--opt1"`
Subcmd  *Subcmd1 `arg:"subcommand:subcmd1"`
}
type Arg2 struct {
Option2 string `arg:"--opt2"`
}
func main() {
var arg1 Arg1
var arg2 Arg2
arg.MustParse(&arg1, &arg2)
}
```
*Output*
```
> tst --help
Usage: tst [--opt1 OPT1] [--opt2 OPT2] <command> [<args>]
Options:
--opt1 OPT1
--opt2 OPT2
--help, -h             display this help and exit
Commands:
subcmd1
> tst subcmd1 --help
Usage: tst subcmd1
Global options:
--opt1 OPT1
--help, -h             display this help and exit
```
*Expected*
```
> tst subcmb1 --help
Usage: tst subcmd1
Global options:
--opt1 OPT1
--opt2 OPT2
--help, -h             display this help and exit
```
When creating the command structure …
=> Fix Missing Global Options

parse.go, parse_test.go
Fixes #60 #284 
The main corner case I'm considering in this PR is when there are arguments like `-4`, `-6` defined as flags, as in
```go
UseIPv4 bool `arg:"-4"`
UseIPv6 bool `arg:"-6"`
}
```
There are a few core linux utilities such as `ping` that set a precedent for having numeric flags like this, so it's a case I do want to support. However, supporting this means that if you have an argument struct like this:
```go
Floats []float64 `arg:"--floats"`
UseIPv4 bool `arg:"-4"`
UseIPv6 bool `arg:"-6"`
}
```
and you write on the command line `./program --floats -1.2 -3.4 -6`, then there's a question of whether the last `-6` should go into Floats or into UseIPv6 in this example.
What this PR implements is that if you have a numeric flag like UseIPv6 in the …
=> Improve handling of negative numbers
